name: Django CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

defaults:
  run:
    working-directory: ./src

jobs:
  setup-and-linting:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2
        with:
          path: ./src
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
           python-version: '3.9'
      - name: Install python dependencies
        run: |
          pip install poetry poetry-dynamic-versioning
          poetry install
      - name: Lint with flake8 and pylint
        run: |
          source $(poetry env info --path)/bin/activate
          flake8 .
          pylint src/
      - name: Upload src dir as artefact
        uses: actions/upload-artifact@v2
        with:
          name: src
          path: ./src

  run-tests:
    needs: setup-and-linting
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: wagtail-email-subscription
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    strategy:
      fail-fast: true
      matrix:
        python-version: [3.7, 3.8, 3.9]
        django-version: [3.1, 3.2]
        wagtail-version: [2.12, 2.13]
        exclude:
          - django-version: 3.2
            wagtail-version: 2.12
    steps:
      - name: Download src dir
        uses: actions/download-artifact@v2
        with:
          name: src
          path: ./src
      - name: Setup Python 3.x
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install python dependencies
        run: |
          pip install poetry
          poetry install
      - name: Install specific matrix dependencies
        run: |
          source $(poetry env info --path)/bin/activate
          pip install "wagtail~=${{ matrix.wagtail-version }}.0" "django~=${{ matrix.django-version }}.0"
          pip list
      - name: Run the testsuite
        env:
          DJANGO_SETTINGS_MODULE: sandbox.settings.github-ci
        run: |
          source $(poetry env info --path)/bin/activate
          pytest
      - name: Upload coverage to codecov
        uses: codecov/codecov-action@v1
        with:
          fail_ci_if_error: true